# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# This file is generated by device/sharp/PA23/setup-makefiles.sh
PRODUCT_COPY_FILES += \
 vendor/sharp/PA23/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
 vendor/sharp/PA23/proprietary/lib/libbattlog.so:system/lib/libbattlog.so \
 vendor/sharp/PA23/proprietary/lib/libcnefeatureconfig.so:system/lib/libcnefeatureconfig.so \
 vendor/sharp/PA23/proprietary/lib/libstlport.so:system/lib/libstlport.so \
 vendor/sharp/PA23/proprietary/bin/shrevk:system/bin/shrevk \
 vendor/sharp/PA23/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
 vendor/sharp/PA23/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
 vendor/sharp/PA23/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
 vendor/sharp/PA23/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
 vendor/sharp/PA23/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libbccQTI.so:system/vendor/lib/libbccQTI.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
 vendor/sharp/PA23/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
 vendor/sharp/PA23/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
 vendor/sharp/PA23/proprietary/bin/uimd:system/bin/uimd \
 vendor/sharp/PA23/proprietary/bin/charger_monitor:system/bin/charger_monitor \
 vendor/sharp/PA23/proprietary/bin/mvpd:system/bin/mvpd \
 vendor/sharp/PA23/proprietary/etc/firmware/a330_pfp.fw:system/etc/firmware/a330_pfp.fw \
 vendor/sharp/PA23/proprietary/etc/firmware/a330_pm4.fw:system/etc/firmware/a330_pm4.fw \
 vendor/sharp/PA23/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
 vendor/sharp/PA23/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
 vendor/sharp/PA23/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
 vendor/sharp/PA23/proprietary/vendor/lib/libNimsWrap.so:system/vendor/lib/libNimsWrap.so \
 vendor/sharp/PA23/proprietary/bin/thermal-engine:system/bin/thermal-engine \
 vendor/sharp/PA23/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
 vendor/sharp/PA23/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
 vendor/sharp/PA23/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
 vendor/sharp/PA23/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
 vendor/sharp/PA23/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
 vendor/sharp/PA23/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
 vendor/sharp/PA23/proprietary/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
 vendor/sharp/PA23/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt \
 vendor/sharp/PA23/proprietary/bin/time_daemon:system/bin/time_daemon \
 vendor/sharp/PA23/proprietary/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
 vendor/sharp/PA23/proprietary/lib/libshdisp.so:system/lib/libshdisp.so \
 vendor/sharp/PA23/proprietary/bin/qseecomd:system/bin/qseecomd \
 vendor/sharp/PA23/proprietary/bin/rfs_access:system/bin/rfs_access \
 vendor/sharp/PA23/proprietary/bin/rmt_storage:system/bin/rmt_storage \
 vendor/sharp/PA23/proprietary/bin/ptt_socket_app:system/bin/ptt_socket_app \
 vendor/sharp/PA23/proprietary/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
 vendor/sharp/PA23/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
 vendor/sharp/PA23/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libdrmdiag.so:system/vendor/lib/libdrmdiag.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
 vendor/sharp/PA23/proprietary/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libprdrmdecrypt.so:system/vendor/lib/libprdrmdecrypt.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libStDrvInt.so:system/vendor/lib/libStDrvInt.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libtzdrmgenprov.so:system/vendor/lib/libtzdrmgenprov.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libtzplayready.so:system/vendor/lib/libtzplayready.so \
 vendor/sharp/PA23/proprietary/bin/mpdecision:system/bin/mpdecision \
 vendor/sharp/PA23/proprietary/vendor/lib/libqc-opt.so:system/vendor/lib/libqc-opt.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libmm-abl.so:system/vendor/lib/libmm-abl.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libmm-abl-oem.so:system/vendor/lib/libmm-abl-oem.so \
 vendor/sharp/PA23/proprietary/bin/irsc_util:system/bin/irsc_util \
 vendor/sharp/PA23/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libdsnetutils.so:system/vendor/lib/libdsnetutils.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libqmi_csvt_srvc.so:system/vendor/lib/libqmi_csvt_srvc.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
 vendor/sharp/PA23/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so

#Framework
PRODUCT_COPY_FILES += \
 vendor/sharp/PA23/proprietary/framework/qti-telephony-common.jar:system/framework/qti-telephony-common.jar
